[Icon Theme]
Name=Vividity
Comment=Vividity is an icon theme designed by Jason C. McDonald, inspired by the Jared Sot's Vibrancy theme.
Directories=apps/scalable,status/scalable
Inherits=Ambiant-MATE,Humanity-Dark,gnome,breeze-dark,breeze,hicolor

[apps/scalable]
Size=512
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable

[status/scalable]
Size=512
Context=Status
MinSize=16
MaxSize=512
Type=Scalable

[Desktop Entry]
Name[en_US]=index.theme
